### ISSUE TITLE
两台机器训练模型的一些疑问

### ISSUE THREAD

**Issue by kceil** [yjxiong/caffe#137]
yjxiong，你好！

我现在使用您的代码准备在两台机器上实现caffe分布式训练，每台机器只有一个gpu，当我搭建好环境之后，使用mpirun -np 2 -hostfile ... caffe train -solver ...命令时，我在hostfile文件里写入了两台机器的IP，在sovler.prototxt中加入device_id: [0,0]和group_id: [0,1]，出现以下错误：

caffe@Caffe1:~/cifar10$ /home/caffe/openmpi/bin/mpirun -hostfile /home/caffe/hostfile -np 2 /home/caffe/caffe/build/tools/caffe train -solver alexnet_solver_origin.prototxt 
I0122 19:36:17.982347  4868 common.cpp:53] Running parallel training with MPI support!
I0122 19:36:17.982405  4869 common.cpp:53] Running parallel training with MPI support!
I0122 19:36:17.984297  4868 caffe.cpp:137] Using the automatic ordinal info for device id. Possible risk of over number
Setting device 0
Setting device 1
F0122 19:36:18.010408  4869 common.cpp:187] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
    @     0x7f56356d9daa  (unknown)
    @     0x7f56356d9ce4  (unknown)
    @     0x7f56356d96e6  (unknown)
    @     0x7f56356dc687  (unknown)
    @     0x7f5635a96ed0  caffe::Caffe::SetDevice()
    @           0x41038e  train()
    @           0x40e766  main
    @     0x7f563418cf45  (unknown)
    @           0x40ed4b  (unknown)
    @              (nil)  (unknown)
*** Aborted at 1485084978 (unix time) try "date -d @1485084978" if you are using GNU date ***
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node 192.168.77.2 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

当我把sovler.prototxt改成device_id: [0,1]和group_id: [0,0]，出现以下错误：
caffe@Caffe1:~/cifar10$ /home/caffe/openmpi/bin/mpirun -hostfile /home/caffe/hostfile -np 2 /home/caffe/caffe/build/tools/caffe train -solver alexnet_solver_origin.prototxt 
I0122 19:35:09.413415  4417 common.cpp:53] Running parallel training with MPI support!
I0122 19:35:09.413496  4418 common.cpp:53] Running parallel training with MPI support!
I0122 19:35:09.415339  4417 caffe.cpp:137] Using the automatic ordinal info for device id. Possible risk of over number
Setting device 0
Setting device 1
F0122 19:35:09.440520  4418 common.cpp:187] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
    @     0x7fc83ac12daa  (unknown)
    @     0x7fc83ac12ce4  (unknown)
    @     0x7fc83ac126e6  (unknown)
    @     0x7fc83ac15687  (unknown)
    @     0x7fc83afcfed0  caffe::Caffe::SetDevice()
    @           0x41038e  train()
    @           0x40e766  main
    @     0x7fc8396c5f45  (unknown)
    @           0x40ed4b  (unknown)
    @              (nil)  (unknown)
*** Aborted at 1485084909 (unix time) try "date -d @1485084909" if you are using GNU date ***
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node 192.168.77.2 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

hostfile的内容：
192.168.77.2
192.168.77.1

当我把hostfile的两行内容调换之后：在192.168.77.1的GPU上出现了两个caffe进程，而192.168.77.2上的GPU并没有进程。

两台机器在本地使用mpirun -np 1的时候均可以进行caffe训练，mpi_hello_world也可以在两台机器上单独和共同并行运行。

我想问一下，是不是在配置的地方出了什么问题，或者是使用什么指令可以在两台只有一个GPU的机器上进行分布式训练，谢谢！

**Comment by yjxiong** [comment]
```
I0122 19:36:17.984297 4868 caffe.cpp:137] Using the automatic ordinal info for device id. Possible risk of over number
```

This line means the framework did not find any information on which device IDs to use. Are you sure you are using the correct solver file? To do distributed training, all nodes must use the same solver file.

**Comment by kceil** [comment]
Thank you for your reply @yjxiong！I put the same solver file on all nodes and it works , Thank you !
Now I find another question,When I use resized cifar10 data to finetune the googLenet based on quick_solver.prototxt , I find that time cost on two machines each iteration is longer than one machines , how can I accelerate the training speed ?

Here is my training info:
Data : cifar-10 resize to 227*227 , LMDB , train data size : 7.8GB , val data size : 1.6GB
quick_solver and net prototxt files are the same as path caffe/models/bvlc_googlenet file
use two machines,each contains one GPU(Quadro K4200)

Thank you again ! Happy Chinese New Year !

**Comment by yjxiong** [comment]
The speed highly depends on the interconnect speed. For example, if it is only 1GB ethernet, the communication overhead can be too high for any acceleration to be observed.

**Comment by kceil** [comment]
你好，我按照您的建议，将其部署在拥有万兆网络的机器上，结果发现在用前面提到的数据finetune模型的时候，两台机器的时间还是会长于一台机器，接着我把两块GPU加在同一台机器上，发现同一台机器的两个GPU的加速效果还是慢于单个GPU训练的结果，我想问一下具体是什么原因导致训练速度较慢的，还是需要添加什么参数？
ALexNet：cifar-10 resize to 227*227 , LMDB , train data size : 7.8GB , val data size : 1.6GB
20次迭代，单台单个GPU需要35秒，单台多个GPU需要37秒，两台单独GPU需要42秒。
两块GPU都是Quadro K4200
请问这个速度是正常的么还是有什么问题？
谢谢~

**Comment by yjxiong** [comment]
Did you reduce the batchsize by 2 when using 2 GPUs?

**Comment by kceil** [comment]
没有 我用的是同一个prototxt 两个gpu训练在solver.prototxt加入了device_id参数。是不是需要把batchsize调整为原来的一半？

**Comment by yjxiong** [comment]
Yes. You need to keep the effective batchsize `batchsize*num_device*iter_size` to be the same.

**Comment by kceil** [comment]
这两天有点忙 刚刚弄了一下 发现的确如你所说 谢谢！
