### ISSUE TITLE
optimized memory and cudnn convolution with dilation

### ISSUE THREAD

**Issue by animebing** [yjxiong/caffe#161]
when i am using your code to train resnet 101 with dilation, i come across some issues below
1.during the training, there is an error 
`F0508 12:39:19.659293 20250 cudnn_conv_layer.cu:117] Check failed: status = =CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM`
by debugging, i find the error comes from the backward  of convolution layer with dilation, then i add "engine: CAFFE" to all convolution layers with dilation, the error is missing, so i want to know whether this error is coming from cudnn 5
2. when i train the network with optimize_train to be true(this is the default setting), in the log, I find 
    `raw memory 11749479328(10.9G) opt memory 3861613284(3.6G)`
but by nvidia-smi,  i find the memory used is 9.6G, which is much larger than above 3.6G, i am really confused about it, can you explain it?

i am looking forward to your reply, thank you.

**Comment by yjxiong** [comment]
1. Dilation is not supported by cuDNN v5. So adding `engine: CAFFE` is correct. If you like you can use the cuDNN v6 branch, where dilation is supported by cuDNN libs. It is claimed to bring some acceleration on Pascal GPUs.

2. Please be noted that Caffe builds separate `net` instances for training and validation. So if you did not set `optimize_test` to `true`, the test net (validation) will take some amount of memory.

**Comment by animebing** [comment]
@yjxiong Thank you for adding the cuDNN v6 branch first. In above, you said the test net will take some amount of memory, but there is no test network in my prototxt, so the extra memory is not caused by the test network. I still have some other questions.
1. When I compile your code with OpenMPI, the compiling process is normal, but when I use the code to train my network, there is the error below
`symbol lookup error: /home/bingbing/git/yjxiong/caffe/install/bin/caffe: undefined symbol: 
 ZN5caffe9SGDSolverIfE19SnapshotSolverStateEPNS_11SolverStateE`
I have search it in google for the whole day, but I can't find any useful solutions
2. I almost know nothing about OpenMPI, I just write some simple code in python to see how OpenMPI works, I find that OpenMPI will create more processes and use more CPU cores, so here you use OpenMPI for gathering the data from multiple GPU, which confuses me about how it works in your code, can you explain a little more?
3. From your source code, I find a sync_bn_layer, so during training a network with batch normalization, if I want to use all data in different GPU to update the BN parameters, like mean and variance, do I have to use the sync_bn_layer instead of ordinary BN layer?

Looking forward to your answers to these questions, thank you very much.

**Comment by yjxiong** [comment]
1. If there is only the train net, the memory footprint for training should be similar to what the log says. The reason for the increase could be the use of Caffe engine for convolution. It will use a large amount of memory for column buffer.

2. The linking problem should be gone when you clean up the build directory and start again.

3. Here MPI is responsible for spawning one process for each GPU and the communication between the GPUs.

4. Yes. SyncBN is devised for the purpose of synchronizing the statistics during the forward process.

**Comment by animebing** [comment]
@yjxiong Thanks for your reply, about the 2nd answer, I clean up the build directory and start again, when I run the mnist example, the error is still here, and I find if I cmake without -DUSE_MPI=ON, there will be no error when I run the mnist example, so maybe the error results from cmake with openmpi?

**Comment by yjxiong** [comment]
`ZN5caffe9SGDSolverIfE19SnapshotSolverStateEPNS_11SolverStateE` this symbol in Caffe's codebase. If linking MPI interrupts its loading, can check a few things

1. Whether there are multiple versions of MPI
2. Whether there are multiple versions of Caffe
3. `ldd -r /home/bingbing/git/yjxiong/caffe/install/bin/caffe` to see which library your caffe binary links to.

**Comment by animebing** [comment]
@yjxiong Thanks for your help, I have solved the problem, the reason is that I have multiple versions of Caffe, and the executable caffe links to other libcaffe.so, which causes the error.

**Comment by yjxiong** [comment]
Good to know.

Closing this. Please feel free to reopen it if you meet any further problem.

**Comment by animebing** [comment]
When I compute the diff for the bottom of bn layer, I find that the result in cudnn engine is much larger than that in caffe engine, which results in gradient explosion in former layer, and the same phenomenon occurs when I use SyncBN layer, so I hope you can check your code again to see whether there is something wrong, thanks

**Comment by animebing** [comment]
@yjxiong When I compute the diff for the bottom of bn layer, I find that the result in cudnn engine is much larger than that in caffe engine, which results in gradient explosion in former layer, and the same phenomenon occurs when I use SyncBN layer, so I hope you can check your code again to see whether there is something wrong, thanks

**Comment by LeeCheer00** [comment]
> @yjxiong Thanks for your help, I have solved the problem, the reason is that I have multiple versions of Caffe, and the executable caffe links to other libcaffe.so, which causes the error.

would you please tell me how to solve the problem, I have 2 caffe (one cpu , one gpu)in my ubuntu.
